# Configuração do DataSource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/arq_soft
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Cria ou atualiza o schema automaticamente ao iniciar (bom para desenvolvimento)
spring.jpa.hibernate.ddl-auto=update 
# Mostra os SQLs gerados no console (útil para debug)
spring.jpa.show-sql=true             
# Formata o SQL no console
spring.jpa.properties.hibernate.format_sql=true 

# Configurações do Servidor Web (opcional)
# server.port=8080 

# Chave secreta para assinatura do JWT (substitua por um valor seguro e complexo em produção!)
jwt.secret=MinhaChaveSecretaMuitoLongaParaSerSeguraNaoUseEstaEmProducao12345 

# Útil para problemas de tipo/binding
logging.level.org.hibernate.type.descriptor.sql=TRACE 

# Ativar log DEBUG para Spring Security
logging.level.org.springframework.security=DEBUG 